
const TIME_PAGE_TRANSITION_ON_REGISTER=4500
// tx poller
const TXREQSTATUS_POLL_INTERVAL = 3000
const TXREQSTATUS_BLOCKCOUNT = 1 // 2 // 4 // 6
let TX_POLL_OPTIONS={
	interval : TXREQSTATUS_POLL_INTERVAL
	, blocksToWait : TXREQSTATUS_BLOCKCOUNT
}

export {
	TIME_PAGE_TRANSITION_ON_REGISTER
	, TX_POLL_OPTIONS
}
