
const MAP_SALETYPES={
	COMMON :'Spot'
	, AUCTION_ENGLISH : 'Auction'

}
const MAP_ITEMHISTORY_EVETNS ={
	REGISTER_ITEM : 'Minted'
	, COMMON :'Listed'
	, AUCTION_ENGLISH : 'Auction'
	, CLOSE_SALE : 'Bought'
	, BID_TO_AUCTION : 'Bid'
}
export {
	MAP_SALETYPES
	, MAP_ITEMHISTORY_EVETNS 
}